//This file is auto-generated.
#pragma once

#include "Audio.h"
#include "CellRenderer.h"
#include "CharacterController.h"
#include "Chess.h"
#include "Clipboard.h"
#include "ConRegistry.h"
#include "Console.h"
#include "ConsoleEngine.h"
#include "ConsoleGameEngine.h"
#include "Database.h"
#include "Debug.h"
#include "EventSystem.h"
#include "File.h"
#include "GDIRenderer.h"
#include "GridRenderer.h"
#include "Input.h"
#include "Math.h"
#include "Maze.h"
#include "MessageBox.h"
#include "MinConsoleNative.h"
#include "MinDefines.h"
#include "NativeRenderer.h"
#include "Navigation.h"
#include "ObjectPool.h"
#include "PaletteSystem.h"
#include "Process.h"
#include "Random.h"
#include "Singleton.h"
#include "String.h"
#include "TextLayout.h"
#include "Timer.h"
#include "UnusualMethods.h"
#include "Utils.h"
#include "Vector.h"
#include "Vector2.h"
#include "Vector3.h"
#include "VTConverter.h"
#include "Window.h"
#include "WinNetwork.h"
#include "WinVersion.h"
#ifdef _MSC_VER
#pragma comment(lib, "MinConsoleNative.lib");
#endif
using namespace MinConsoleNative;
