//This file is auto-generated.
#pragma once

#include "Audio.h"
#include "Clipboard.h"
#include "ConRegistry.h"
#include "Console.h"
#include "Database.h"
#include "Debug.h"
#include "File.h"
#include "Input.h"
#include "Math.h"
#include "MessageBox.h"
#include "MinConsoleNative.h"
#include "MinDefines.h"
#include "ObjectPool.h"
#include "PixelRenderer.h"
#include "Process.h"
#include "Random.h"
#include "Singleton.h"
#include "String.h"
#include "TextLayout.h"
#include "TextRenderer.h"
#include "Timer.h"
#include "UnusualMethods.h"
#include "Utils.h"
#include "Vector2.h"
#include "Vector3.h"
#include "VTConverter.h"
#include "Window.h"
#include "WinVersion.h"
using namespace MinConsoleNative;
