using System;
using System.Runtime.InteropServices;

namespace MinConsole
{
    //This class is auto generated by NativeFunctionTranslator.
    public static partial class MinConsoleNativeStructs
    {
        public enum ConsoleType
        {
            Unknown = 0,
            WindowsLegacyConsole = 1,
            WindowsConsole = 2,
            WindowsTerminal = 4,
        }

        public enum ConsoleFile
        {
            Read = 1,
            Write = 2,
        }

        public enum CharWidth
        {
            Unknown = 0,
            Half = 1,
            Full = 2,
        }

        public enum ConsoleColor
        {
            BLACK = 0,
            DARKBLUE = 1,
            DARKGREEN = 2,
            DARKCYAN = 3,
            DARKRED = 4,
            DARKMAGENTA = 5,
            DARKYELLOW = 6,
            GRAY = 7,
            DARKGRAY = 8,
            BLUE = 9,
            GREEN = 10,
            CYAN = 11,
            RED = 12,
            MAGENTA = 13,
            YELLOW = 14,
            WHITE = 15,
        }

        public enum MouseWheelDirection
        {
            None = 0,
            Up = 1,     //The mouse wheel turns away from the player
            Down = 2,   //The mouse wheel turns towards the player
        }

        public enum MouseAxis
        {
            MOUSE_X = 1,
            MOUSE_Y = 2,
        }

        public enum MessageBoxButtons
        {
            OK = 1,
            OKCANCEL,
            YESNO,
            YESNOCANCEL,
        }

        public enum MessageBoxDefaultButton
        {
            First = 1,
            Second,
            Third,
        }

        public enum MessageBoxIcon
        {
            Warning = 1,
            Information,
            Error,
        }

        public enum MessageBoxResult
        {
            OK = 1,
            YES,
            NO,
            CANCEL,
        }

        public enum TerminalColor
        {
            Black = 0,
            DarkBlue = 4,
            DarkGreen = 2,
            DarkCyan = 6,
            DarkRed = 1,
            DarkMagenta = 5,
            DarkYellow = 3,
            Gray = 7,
            DarkGray = 8,
            Blue = 12,
            Green = 10,
            Cyan = 14,
            Red = 9,
            Magenta = 13,
            Yellow = 11,
            White = 15,
        }

    }
}
